// // pages/_app.js

// import AuthProvider from '@/app/Components/Auth/Providers/AuthProvider';
// import '../app/globals.css';

// const MyApp = ({ Component, pageProps }) => {
//     const metadata = {
//         title: "Create Next App",
//         description: "Generated by create next app",
//     };

//     return (
//         <AuthProvider>
//             <Component {...pageProps} metadata={metadata} />
//         </AuthProvider>
//     );
// }

// export default MyApp;
